name: cookandchill
description: A simple meal planner.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^1.2.1
  path_provider: ^2.0.8
  google_fonts: ^2.3.1
  palette_generator: ^0.3.2
  intl: ^0.17.0
  ez_localization: ^1.0.0
  animated_text_kit: ^4.2.1
  provider: ^6.0.2
  file_picker: ^4.3.3
  sticky_headers: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/languages/
    - assets/lottie/
    - assets/recipes/
